import { AssetItem, CashMovement, CheckItem, Invoice, InvoiceItem, LinkedOperation, ProductItem } from "../types";

export const invoiceToRow = (invoice: Invoice) => ({
  id: invoice.id,
  company_id: invoice.companyId,
  invoice_type: invoice.invoiceType,
  operation_type: invoice.operationType,
  invoice_number: invoice.invoiceNumber,
  series: invoice.series,
  access_key: invoice.accessKey,
  issue_date: invoice.issueDate,
  entry_date: invoice.entryDate || null,
  exit_date: invoice.exitDate || null,
  party_name: invoice.partyName,
  party_cnpj: invoice.partyCnpj,
  party_ie: invoice.partyIe || null,
  city: invoice.city,
  state: invoice.state,
  nature_operation: invoice.natureOperation,
  main_cfop: invoice.mainCfop,
  purpose: invoice.purpose,
  payment_condition: invoice.paymentCondition,
  payment_method: invoice.paymentMethod,
  due_date: invoice.dueDate || null,
  pf_value: invoice.pfValue || 0,
  carrier_name: invoice.carrierName || null,
  payment_date: invoice.paymentDate || null,
  paid: invoice.paid,
  status: invoice.status,
  category: invoice.category || null,
  cost_center: invoice.costCenter || null,
  total_products: invoice.totalProducts,
  freight_value: invoice.freightValue,
  discount_value: invoice.discountValue || 0,
  retention_type: invoice.retentionType || null,
  retention_value: invoice.retentionValue || 0,
  total_invoice: invoice.totalInvoice,
  icms_base: invoice.icmsBase,
  icms_value: invoice.icmsValue,
  icms_credit_value: invoice.icmsCreditValue,
  pis_base: invoice.pisBase,
  pis_value: invoice.pisValue,
  pis_credit_value: invoice.pisCreditValue,
  cofins_base: invoice.cofinsBase,
  cofins_value: invoice.cofinsValue,
  cofins_credit_value: invoice.cofinsCreditValue,
  cfem_base: invoice.cfemBase,
  cfem_rate: invoice.cfemRate,
  cfem_value: invoice.cfemValue,
  tax_benefit: invoice.taxBenefit || null,
  legal_basis: invoice.legalBasis || null,
  additional_info: invoice.additionalInfo || null,
  internal_notes: invoice.internalNotes || null,
  xml_file_name: invoice.xmlFileName || null,
  pdf_file_name: invoice.pdfFileName || null,
  has_linked_operation: invoice.hasLinkedOperation,
  linked_operation_type: invoice.linkedOperationType || null,
  linked_invoice_number: invoice.linkedInvoiceNumber || null,
  final_recipient_name: invoice.finalRecipientName || null,
  physical_receiver_name: invoice.physicalReceiverName || null,
  created_at: invoice.createdAt,
  updated_at: invoice.updatedAt,
  items: invoice.items,
  financial_installments: invoice.financialInstallments || [],
});

export const rowToInvoice = (row: Record<string, any>): Invoice => ({
  id: row.id,
  companyId: row.company_id,
  invoiceType: row.invoice_type,
  operationType: row.operation_type,
  invoiceNumber: row.invoice_number,
  series: row.series,
  accessKey: row.access_key || "",
  issueDate: row.issue_date,
  entryDate: row.entry_date || undefined,
  exitDate: row.exit_date || undefined,
  partyName: row.party_name,
  partyCnpj: row.party_cnpj,
  partyIe: row.party_ie || undefined,
  city: row.city,
  state: row.state,
  natureOperation: row.nature_operation,
  mainCfop: row.main_cfop,
  purpose: row.purpose,
  paymentCondition: row.payment_condition,
  paymentMethod: row.payment_method,
  dueDate: row.due_date || undefined,
  pfValue: Number(row.pf_value || 0),
  carrierName: row.carrier_name || undefined,
  paymentDate: row.payment_date || undefined,
  paid: Boolean(row.paid),
  status: row.status,
  category: row.category || undefined,
  costCenter: row.cost_center || undefined,
  totalProducts: Number(row.total_products || 0),
  freightValue: Number(row.freight_value || 0),
  discountValue: Number(row.discount_value || 0),
  retentionType: row.retention_type || undefined,
  retentionValue: Number(row.retention_value || 0),
  totalInvoice: Number(row.total_invoice || 0),
  icmsBase: Number(row.icms_base || 0),
  icmsValue: Number(row.icms_value || 0),
  icmsCreditValue: Number(row.icms_credit_value || 0),
  pisBase: Number(row.pis_base || 0),
  pisValue: Number(row.pis_value || 0),
  pisCreditValue: Number(row.pis_credit_value || 0),
  cofinsBase: Number(row.cofins_base || 0),
  cofinsValue: Number(row.cofins_value || 0),
  cofinsCreditValue: Number(row.cofins_credit_value || 0),
  cfemBase: Number(row.cfem_base || 0),
  cfemRate: Number(row.cfem_rate || 0),
  cfemValue: Number(row.cfem_value || 0),
  taxBenefit: row.tax_benefit || undefined,
  legalBasis: row.legal_basis || undefined,
  additionalInfo: row.additional_info || undefined,
  internalNotes: row.internal_notes || undefined,
  xmlFileName: row.xml_file_name || undefined,
  pdfFileName: row.pdf_file_name || undefined,
  hasLinkedOperation: Boolean(row.has_linked_operation),
  linkedOperationType: row.linked_operation_type || undefined,
  linkedInvoiceNumber: row.linked_invoice_number || undefined,
  finalRecipientName: row.final_recipient_name || undefined,
  physicalReceiverName: row.physical_receiver_name || undefined,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  items: (row.items || []) as InvoiceItem[],
  financialInstallments: row.financial_installments || [],
});

export const operationToRow = (op: LinkedOperation) => ({
  id: op.id,
  company_id: op.companyId,
  operation_type: op.operationType,
  main_invoice_id: op.mainInvoiceId || null,
  linked_invoice_id: op.linkedInvoiceId || null,
  main_invoice_number: op.mainInvoiceNumber,
  linked_invoice_number: op.linkedInvoiceNumber,
  supplier_name: op.supplierName,
  final_recipient_name: op.finalRecipientName,
  final_recipient_cnpj: op.finalRecipientCnpj,
  physical_receiver_name: op.physicalReceiverName,
  physical_receiver_cnpj: op.physicalReceiverCnpj,
  main_cfop: op.mainCfop,
  linked_cfop: op.linkedCfop,
  main_access_key: op.mainAccessKey || null,
  linked_access_key: op.linkedAccessKey || null,
  operation_date: op.operationDate,
  amount: op.amount,
  status: op.status,
  notes: op.notes,
  created_at: op.createdAt,
  updated_at: op.updatedAt,
});

export const rowToOperation = (row: Record<string, any>): LinkedOperation => ({
  id: row.id,
  companyId: row.company_id,
  operationType: row.operation_type,
  mainInvoiceId: row.main_invoice_id || undefined,
  linkedInvoiceId: row.linked_invoice_id || undefined,
  mainInvoiceNumber: row.main_invoice_number,
  linkedInvoiceNumber: row.linked_invoice_number,
  supplierName: row.supplier_name,
  finalRecipientName: row.final_recipient_name,
  finalRecipientCnpj: row.final_recipient_cnpj,
  physicalReceiverName: row.physical_receiver_name,
  physicalReceiverCnpj: row.physical_receiver_cnpj,
  mainCfop: row.main_cfop,
  linkedCfop: row.linked_cfop,
  mainAccessKey: row.main_access_key || undefined,
  linkedAccessKey: row.linked_access_key || undefined,
  operationDate: row.operation_date,
  amount: Number(row.amount || 0),
  status: row.status,
  notes: row.notes || "",
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const assetToRow = (asset: AssetItem) => ({
  id: asset.id,
  item_type: asset.itemType,
  item_name: asset.itemName,
  acquisition_date: asset.acquisitionDate,
  acquisition_value: asset.acquisitionValue,
  plate: asset.plate || null,
  registration_number: asset.registrationNumber || null,
  archived: asset.archived,
  created_at: asset.createdAt,
  updated_at: asset.updatedAt,
});

export const rowToAsset = (row: Record<string, any>): AssetItem => ({
  id: row.id,
  itemType: row.item_type,
  itemName: row.item_name,
  acquisitionDate: row.acquisition_date,
  acquisitionValue: Number(row.acquisition_value || 0),
  plate: row.plate || undefined,
  registrationNumber: row.registration_number || undefined,
  archived: Boolean(row.archived),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const cashMovementToRow = (movement: CashMovement) => ({
  id: movement.id,
  movement_type: movement.movementType,
  cash_scope: movement.cashScope || "normal",
  movement_date: movement.date,
  holder: movement.holder,
  destination_holder: movement.destinationHolder || null,
  cost_center: movement.costCenter || null,
  destination_cost_center: movement.destinationCostCenter || null,
  history: movement.history || "",
  amount: movement.amount,
  created_at: movement.createdAt,
  updated_at: movement.updatedAt,
});

export const rowToCashMovement = (row: Record<string, any>): CashMovement => ({
  id: row.id,
  movementType: row.movement_type,
  cashScope: row.cash_scope || "normal",
  date: row.movement_date,
  holder: row.holder || "",
  destinationHolder: row.destination_holder || undefined,
  costCenter: row.cost_center || "",
  destinationCostCenter: row.destination_cost_center || undefined,
  history: row.history || "",
  amount: Number(row.amount || 0),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const productToRow = (product: ProductItem) => ({
  id: product.id,
  product_code: product.code || null,
  name: product.name,
  ncm: product.ncm || null,
  default_cost_center: product.defaultCostCenter || null,
  default_category: product.defaultCategory || null,
  default_unit: product.defaultUnit || null,
  accounting_account: product.accountingAccount || null,
  color: product.color || null,
  active: product.active,
  created_at: product.createdAt,
  updated_at: product.updatedAt,
});

export const rowToProduct = (row: Record<string, any>): ProductItem => ({
  id: row.id,
  code: row.product_code || "",
  name: row.name,
  ncm: row.ncm || "",
  defaultCostCenter: row.default_cost_center || "",
  defaultCategory: row.default_category || "",
  defaultUnit: row.default_unit || "UN",
  accountingAccount: row.accounting_account || "",
  color: row.color || "",
  active: Boolean(row.active),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

export const checkToRow = (check: CheckItem) => ({
  id: check.id,
  check_number: check.checkNumber,
  amount: check.amount,
  issuer_name: check.issuerName,
  issuer_document: check.issuerDocument || null,
  bank: check.bank || null,
  agency: check.agency || null,
  account: check.account || null,
  due_date: check.dueDate,
  received_date: check.receivedDate,
  received_from: check.receivedFrom,
  passed_date: check.passedDate || null,
  passed_to: check.passedTo || null,
  deposit_date: check.depositDate || null,
  deposit_holder: check.depositHolder || null,
  deposit_agency: check.depositAgency || null,
  deposit_account: check.depositAccount || null,
  compensation_date: check.compensationDate || null,
  compensation_holder: check.compensationHolder || null,
  returned_date: check.returnedDate || null,
  returned_reason: check.returnedReason || null,
  recovered_date: check.recoveredDate || null,
  recovered_from: check.recoveredFrom || null,
  recovery_reason: check.recoveryReason || null,
  canceled_date: check.canceledDate || null,
  canceled_reason: check.canceledReason || null,
  related_invoices: check.relatedInvoices || [],
  notes: check.notes || null,
  status: check.status,
  movements: check.movements || [],
  created_at: check.createdAt,
  updated_at: check.updatedAt,
});

export const rowToCheck = (row: Record<string, any>): CheckItem => ({
  id: row.id,
  checkNumber: row.check_number,
  amount: Number(row.amount || 0),
  issuerName: row.issuer_name,
  issuerDocument: row.issuer_document || "",
  bank: row.bank || "",
  agency: row.agency || "",
  account: row.account || "",
  dueDate: row.due_date,
  receivedDate: row.received_date,
  receivedFrom: row.received_from || "",
  passedDate: row.passed_date || undefined,
  passedTo: row.passed_to || undefined,
  depositDate: row.deposit_date || undefined,
  depositHolder: row.deposit_holder || undefined,
  depositAgency: row.deposit_agency || undefined,
  depositAccount: row.deposit_account || undefined,
  compensationDate: row.compensation_date || undefined,
  compensationHolder: row.compensation_holder || undefined,
  returnedDate: row.returned_date || undefined,
  returnedReason: row.returned_reason || undefined,
  recoveredDate: row.recovered_date || undefined,
  recoveredFrom: row.recovered_from || undefined,
  recoveryReason: row.recovery_reason || undefined,
  canceledDate: row.canceled_date || undefined,
  canceledReason: row.canceled_reason || undefined,
  relatedInvoices: row.related_invoices || [],
  notes: row.notes || "",
  status: row.status,
  movements: row.movements || [],
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});
